apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blob-storage
  namespace: default
spec:
  type: bindings.azure.blobstorage
  metadata:
  - name: storageAccount
    value: STORAGE_ACCOUNT_NAME
  - name: storageAccessKey
    value: STORAGE_ACCOUNT_ACCESS_KEY
  - name: container
    value: orders